### ISSUE TITLE
Validation option

### ISSUE THREAD

**Issue by nivalamata** [ileghlam/findOrCreate#4]
i want to show validation error during create or update if I set validate as option to true

**Comment by rle-mino** [comment]
This package is no longer maintained (maybe we should update the readme).

If you want to find things and create them if they don't exist, you can use the "native" mongoose.Model('yourModel').findOneAndUpdate.

You can find a complete documentation [here](http://mongoosejs.com/docs/api.html#findoneandupdate_findOneAndUpdate)

```javascript
mongoose.model('yourModel').findOrCreate({ ...stuffToFind }, { ...stuffToInsert })
  .then((doc) => {})
```
is the same as
```javascript
mongoose.model('yourModel').findOneAndUpdate({ ...stuffToFind }, { ...stuffToInsert }, { upsert: true, new: true })
  .then((doc) => {})
```

**Comment by nivalamata** [comment]
thanks for feedback,  very helpful.....
